practice/linker/urls.py
from django.urls import path
from . import views

app_name = "linker"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add_message/", views.add_message, name="add_message"),
    path(
        "message/<int:message_id>/add_comment/", views.add_comment, name="add_comment"
    ),
    path("message/<int:message_id>/vote/", views.vote, name="vote"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("message/<int:pk>/", views.MessageView.as_view(), name="message_detail"),
]

practice/practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("linker.urls")),
]

handler404 = "linker.views.page_not_found_view"

practice/linker/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class CommonTextModel(models.Model):
    text_content = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    votes = models.SmallIntegerField(default=0)

    def formatted_date(self):
        return self.pub_date.strftime("%d/%m/%Y | %H:%M")

    class Meta:
        abstract = True


class Message(CommonTextModel):
    message_title = models.CharField(max_length=100)

    def __str__(self):
        return self.formatted_date() + " || " + self.message_title


class Comment(CommonTextModel):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)

    def __str__(self):
        str_self_text = self.text_content
        if len(str_self_text) > 40:
            str_self_text = str_self_text[:40] + "..."

        return self.formatted_date() + " || " + str_self_text

practice/linker/views.py
from django.http import HttpResponse, HttpResponseRedirect
from .models import Message, Comment
from django.views import generic
from django.urls import reverse
from django.shortcuts import get_object_or_404

# Create your views here.
class IndexView(generic.ListView):
    template_name = "linker/index.html"
    context_object_name = "message_list"

    def get_queryset(self):
        return list(
            map(
                lambda message: {
                    "id": message.id,
                    "message_title": message.message_title,
                    "formatted_date": message.formatted_date,
                    "votes": message.votes,
                    "comments_num": len(message.comment_set.all()),
                },
                Message.objects.all(),
            )
        )


class MessageView(generic.DetailView):
    template_name = "linker/message_detail.html"
    model = Message

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comments"] = context["message"].comment_set.all()
        context["comments_num"] = len(context["comments"])
        return context


def add_message(request):
    message = Message(
        message_title=request.POST["message_title"],
        text_content=request.POST["message_text"],
    )
    message.save()
    return HttpResponseRedirect(reverse("linker:index"))


def add_comment(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    comment = Comment(text_content=request.POST["comment"], message=message)
    comment.save()
    return HttpResponseRedirect(reverse("linker:message_detail", args=(message.id,)))


def vote(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    if "upvote" in request.POST:
        message.votes += 1
    elif "downvote" in request.POST:
        message.votes -= 1
    message.save()

    return HttpResponseRedirect(reverse("linker:index"))


def contact(request):
    return HttpResponse("Contact me here.")


def about(request):
    return HttpResponse("Find out more about me.")


def page_not_found_view(request, exception=None):
    return HttpResponse("Wrong page.", status=404)

practice/linker/templates/linker/index.html
<div>
  <h1>Message Feed</h1>
  {% if message_list %}
  <ul>
    {% for message in message_list %}
    <li>
      <span> {{message.formatted_date}} -- </span>
      <a href="{% url 'linker:message_detail' message.id %}"
        >{{message.message_title}}
      </a>
      <div>Votes: {{message.votes}} | Comments: {{message.comments_num}}</div>
    </li>
    <form action="{% url 'linker:vote' message.id%}" method="post">
      {% csrf_token %}
      <button type="submit" name="upvote">Upvote</button>
      <button type="submit" name="downvote">Downvote</button>
    </form>
    {%endfor%}
  </ul>
  {%endif%}
</div>
<div>
  <h1>Add a message</h1>
  <form action="{% url 'linker:add_message'%}" method="post">
    {% csrf_token %}
    <div>
      <label for="message_title">Title</label>
      <input type="text" name="message_title" />
    </div>
    <br /><br /><br />
    <div>
      <label for="message_text">Message</label>
      <textarea type="text" name="message_text" rows="5" cols="50"></textarea>
    </div>
    <br /><br /><br />
    <input type="submit" />
  </form>
</div>

<div>
  <div><a href="{% url 'linker:about'%}">About</a></div>
  <div><a href="{% url 'linker:contact'%}">Contact</a></div>
</div>

practice/linker/templates/linker/message_detail.html
<div>{{message.formatted_date}}</div>
<h1>{{message.message_title}}</h1>
<p>{{message.text_content}}</p>
<div>Votes: {{message.votes}} | Comments: {{comments_num}}</div>
{% if comments_num > 0 %}
<ul>
  {%for comment in comments%}
  <li>
    <p>{{comment.text_content}}</p>
    <div>{{comment.formatted_date}} | {{comment.votes}} votes</div>
  </li>
  {%endfor%}
</ul>
{%endif %}
<div>
  <h1>Add comment</h1>
  <form action="{% url 'linker:add_comment' message.id%}" method="post">
    {% csrf_token %}
    <textarea name="comment" id="" cols="30" rows="10"></textarea>
    <br /><br />
    <input type="submit" />
  </form>
</div>